name: autoTest
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run action Test
        run: |
          javac -cp .:lib/* MarkdownParseTest.java

          java  -cp .:lib/*  org.junit.runner.JUnitCore MarkdownParseTest
